/*
*/
set echo on

AUDIT
 ALTER DATABASE,
 ALTER DATABASE LINK,
 ALTER PROFILE,
 ALTER PUBLIC DATABASE LINK,
 ALTER SESSION,
 ALTER SYSTEM,
 ALTER TABLESPACE,
 ALTER USER,
 BECOME USER,
 CREATE SESSION,
 CREATE PUBLIC DATABASE LINK,
 CREATE PUBLIC SYNONYM,
 CREATE JOB,
 CREATE EXTERNAL JOB,
 CREATE DATABASE LINK,
 DROP PUBLIC DATABASE LINK,
 DROP PUBLIC SYNONYM,
 DROP PROFILE,
 DROP USER,
 DROP TABLESPACE
BY ACCESS
/
