CREATE USER tools IDENTIFIED BY "to0ls" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS ACCOUNT UNLOCK;
GRANT CONNECT, ALTER SESSION, CREATE TABLE, SELECT ANY DICTIONARY TO tools;
