#!/bin/bash
# This command performs `git pull --rebase upstream master` only when the current repo has "upstream" remote, has no uncommitted changes and has "master" as a current branch
git remote show upstream 2>/dev/null >/dev/null && [[ ! $(git status --short | grep -q -v '^??') && "$(git rev-parse --abbrev-ref HEAD)" == 'master' ]] && git pull --rebase upstream master && git push
