set echo on

CREATE OR REPLACE DIRECTORY LS_BETA_DATAPUMP_DIR AS '/shared/oracle/backup/LS_BETA';
CREATE OR REPLACE DIRECTORY LS_BUILD_DATAPUMP_DIR AS '/shared/oracle/backup/LS_BUILD';
CREATE OR REPLACE DIRECTORY LS_DEV_DATAPUMP_DIR AS '/shared/oracle/backup/LS_DEV';
CREATE OR REPLACE DIRECTORY LS_PERF_DATAPUMP_DIR AS '/shared/oracle/backup/LS_PERF';
CREATE OR REPLACE DIRECTORY LS_PROD_EDC_DATAPUMP_DIR AS '/shared/oracle/backup/LS_PROD_EDC';
CREATE OR REPLACE DIRECTORY LS_PROD_EAGAN_DATAPUMP_DIR AS '/shared/oracle/backup/LS_PROD_EAGAN';
CREATE OR REPLACE DIRECTORY LS_QA_EDC_DATAPUMP_DIR AS '/shared/oracle/backup/LS_QA_EDC';
CREATE OR REPLACE DIRECTORY SHARED_BACKUP_DIR AS '/shared/oracle/backup';
CREATE OR REPLACE DIRECTORY NG_QA_EDC_DATAPUMP_DIR AS '/shared/oracle/backup/NG_QA_EDC';
CREATE OR REPLACE DIRECTORY NG_QA_EAGAN_DATAPUMP_DIR AS '/shared/oracle/backup/NG_QA_EAGAN';
CREATE OR REPLACE DIRECTORY NG_PROD_EAGAN_DATAPUMP_DIR AS '/shared/oracle/backup/NG_PROD_EAGAN';
CREATE OR REPLACE DIRECTORY NG_PROD_EDC_DATAPUMP_DIR AS '/shared/oracle/backup/NG_PROD_EDC';
CREATE OR REPLACE DIRECTORY NG_BETA_DATAPUMP_DIR AS '/shared/oracle/backup/NG_BETA';
CREATE OR REPLACE DIRECTORY NG_BUILD_DATAPUMP_DIR AS '/shared/oracle/backup/NG_BUILD';
CREATE OR REPLACE DIRECTORY NG_DEV_DATAPUMP_DIR AS '/shared/oracle/backup/NG_DEV';
CREATE OR REPLACE DIRECTORY NG_PERF_DATAPUMP_DIR AS '/shared/oracle/backup/NG_PERF';
CREATE OR REPLACE DIRECTORY GGDB_DATAPUMP_DIR AS '/shared/oracle/backup/GGDB';
CREATE OR REPLACE DIRECTORY JPHARM_DEV_DATAPUMP_DIR AS '/shared/oracle/backup/JPHARM_DEV';
CREATE OR REPLACE DIRECTORY JPHARM_QA_DATAPUMP_DIR AS '/shared/oracle/backup/JPHARM_QA';
CREATE OR REPLACE DIRECTORY JPHARM_PROD_DATAPUMP_DIR AS '/shared/oracle/backup/JPHARM_PROD';

-- CREATE OR REPLACE DIRECTORY DATAPUMP_DIR AS '/shared/oracle/backup/NG_PERF';

set echo off
