RMAN:

SQL "ALTER DATABASE DATAFILE ''&1'' OFFLINE";
COPY DATAFILE '&1' TO '+ORA3';
-- get new name of file from log
REM SQL "ALTER DATABASE RENAME FILE ''&1'' TO ''&2''";
SWITCH DATAFILE '&1' TO COPY;
RECOVER DATAFILE '&2';
SQL "ALTER DATABASE DATAFILE ''&2'' ONLINE";
