CREATE GLOBAL TEMPORARY TABLE MV_CAPABILITIES_TABLE (
  STATEMENT_ID         VARCHAR(30),
  MVOWNER              VARCHAR(30),
  MVNAME               VARCHAR(30),
  CAPABILITY_NAME      VARCHAR(30),
  POSSIBLE             CHARACTER(1),
  RELATED_TEXT         VARCHAR(2000),
  RELATED_NUM          NUMBER,
  MSGNO                INTEGER,
  MSGTXT               VARCHAR(2000),
  SEQ                  NUMBER)
ON COMMIT PRESERVE ROWS;
CREATE OR REPLACE PUBLIC SYNONYM MV_CAPABILITIES_TABLE for SYSTEM.MV_CAPABILITIES_TABLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.MV_CAPABILITIES_TABLE TO PUBLIC;

